sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - .phpunit

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3


matrix:
  fast_finish: true

before_install:
  - export SYMFONY_PHPUNIT_DIR="$(pwd)/.phpunit"
  - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI_FILE
  - phpenv config-rm xdebug.ini

install:
  - composer install

script:
  - ./vendor/bin/simple-phpunit
