services:
    # Seralizer Adapter
    api_response.serializer_adapter:
        class: MattJanssen\ApiResponseBundle\Serializer\Adapter\SerializerAdapterInterface
        synthetic: true

    # Subscribers
    api_response.subscriber.api_response:
        class: MattJanssen\ApiResponseBundle\Subscriber\ApiResponseSubscriber
        tags: [ { name: kernel.event_subscriber } ]
        arguments:
            - @service_container
            - %api_response.default_serializer%
            - %kernel.debug%
