services:
    # Seralizer Adapter
    api_response.serializer_adapter:
        class: MattJanssen\ApiResponseBundle\Serializer\Adapter\SerializerAdapterInterface
        synthetic: true

    # Subscriber
    api_response.subscriber.api_response:
        class: MattJanssen\ApiResponseBundle\Subscriber\ApiResponseSubscriber
        tags: [ { name: kernel.event_subscriber } ]
        arguments:
            - @api_response.generator.api_response
            - %api_response.path_configs%
            - %kernel.debug%

    # Generator
    api_response.generator.api_response:
        class: MattJanssen\ApiResponseBundle\Generator\ApiResponseGenerator
        arguments:
            - @service_container
            - %api_response.default_serializer%

    # Firewall Entry Point
    api_response.entry_point.api_basic:
        class: MattJanssen\ApiResponseBundle\EntryPoint\ApiBasicAuthenticationEntryPoint
        arguments:
            - @api_response.generator.api_response

    # Firewall Access Denied Handler
    api_response.authorization.api_basic_access_denied_handler:
        class: MattJanssen\ApiResponseBundle\Authorization\ApiBasicAccessDeniedHandler
        arguments:
            - @api_response.generator.api_response
